name: BandwidthExtensionRIRs
channels:
  - defaults
dependencies:
  - numpy
  - matplotlib
  - h5py
  - scipy
  - pytorch
  - torchvision
  - tqdm
  - jupyter
  - pip:
    - librosa
    - torchaudio
    - palettable
    - wandb
prefix: /Users/xen/miniconda3/envs/BandwidthExtensionRIRs
